== BUC_EH - Exemplaar Huren

De klant probeert een exemplaar te huren gedurende een bepaalde periode. 
Er moet nagegaan worden of dit mogelijk is en een kost op de lopende rekening geplaatst worden.  

=== Actors

*Klant*, medewerker

=== Preconditie

Klant is geïdentificeerd

=== Basis pad

.   De _klant_ wil een exemplaar huren.
.   De _klant_ geeft het identificatie plaatje van het exemplaar aan de medewerker.
.   De _medewerker_ gaat na dat de klant dit exemplaar mag huren volgens <<domeinregels.adoc#_dr_vev_verhuur_van_een_exemplaar_voor_volwassenen,*DR_VEV*>>.
.   De _klant_ geeft aan hoe lang hij het exemplaar wil houden.
.   De _medewerker_ gaat na dat dit kan gedurenede de gevraagde periode volgens <<domeinregels.adoc#_dr_evp_exemplaar_is_verhuurbaar_gedurende_periode,*DR_EVP*>>.
.   De _medewerker_ gaat na dat de dag waarop het exemplaar teruggebracht moet worden, geen voorziene sluitingsdag is.
.   De _medewerker_ noteert de verhuring.
.   De _medewerker_ voegt de kost toe aan de lopende rekening van de klant volgens <<domeinregels.adoc#_dr_kep_kost_van_een_exemplaar_voor_een_periode,*DR_KEP*>> .
.   De use case eindigt.

==== Postconditie

Het exemplaar is in het bezit van de klant en de kosten zijn aan de lopende rekening van de klant toegevoegd. 
Het exemplaar moet niet teruggebracht worden op een voorziene sluitingsdag.

_Merk op dat stap 6 van het basispad nodig is wegens <<domeinregels.adoc#_dr_vps_verhuurperiode_en_sluitingsdagen,*DR_VPS*>>._

=== Alternatief A: Stoppen

.   De _klant_ kan op elk moment beslissen om te stoppen.
.   De _medewerker_ maakt eventuele wijzigingen ongedaan.
.   De use case eindigt.

==== Postconditie 

Niks gewijzigd.

=== Alternatief B: Mag niet verhuurd worden aan klant

[start=3]
.   De _medewerker_ merkt dat de klant deze titel niet mag huren.
.   De _medewerker_ informeert de klant hierover.
.   De use case eindigt.

==== Postconditie

Niks gewijzigd

=== Alternatief C: Exemplaar niet verhuurbaar gedurende de gevraagde periode

[start=5]
.   De _medewerker_ merkt dat het exemplaar niet verhuurbaar is voor de gevraagde periode.
.   De _medewerker_ informeert de klant hierover en vraagt om een kortere periode.
.   De use case gaat verder in stap 4 van het basispad.

_Merk op dat een gelijkwaardig exemplaar zoeken in alternatief C, zinloos zou zijn vermits <<domeinregels.adoc#_dr_evd_exemplaar_is_verhuurbaar_op_dag,*DR_EVD*>> uitgedrukt is in termen van (alle) gelijkwaardige exemplaren._

=== Alternatief D: Exemplaar moet teruggebracht worden op sluitingsdag.

[start=6]
.   De _medewerker_ merkt dat het exemplaar moet teruggebracht worden op een voorziene sluitingsdag.
.   De _medewerker_ verlengt de verhuurperiode zodanig dat het exemplaar niet meer op een voorziene sluitingsdag moet teruggebracht worden.
.   De _medewerker_ informeert de klant hierover.
.   De use case gaat verder met de volgende stap van het basispad.

_Merk op dat in alternatief D, het exemplaar sowieso verhuurbaar zal zijn op elke voorziene sluitingsdag, er zijn dan immers geen passende reservaties. 
Het is dus zeker dat het exemplaar verhuurbaar zal zijn in de verlengde verhuurperiode._
