=== Definitieve vragen en antwoorden
. Heeft een co-titularis dezelfde rechten als een titularis?
JA

. Op welke basis van welke wisselkoers werkt de bank?
GEEN, ENKEL EURO

. Zijn er vereisten om een rekening te openen?
BELGISCH RIJKSREGISTERNUMMER EN MINSTENS 18 JAAR

. Wat is de limiet voor geld te storten?
GEEN

. Hoef je een zichtrekening hebben om een spaarrekening te opennen bij de bank?
NEEN

. Wat zijn de ‘kosten van schulden’?
ELKE DAG DAT JE REKENING ONDER 0 STAAT, KOST GELD

. Is er een limiet op geldopname?
JE KUNT NIET MEER OPNEMEN DAN JE SALDO (EN EVT KREDIETLIMIET) TOELATEN

. Hoelang duurt en overschijving binnen IBS?
OGENBLIKKELIJK

. Is het mogelijk om meerdere spaarrekeningen te openen?
JA

. Is het mogelijk om meerdere zichtrekeningen te openen?
JA

. Hoeveel rekeningen kun je maximaal hebben?
GEEN LIMIET

. Kan je buitenlandse valuta storten?
NEEN

. Kan je onder 0 gaan op de rekening en wat gebeurt er dan?
OP ZICHTREKENING KAN JE TOT AAN DE KREDIETLIMIET GAAN ONDER NUL

. Is er een limiet op hoeveel geld je kan storten in één keer?
NEEN

. Instapkosten? Kost het geld om een rekening te openen?
NEEN

. Kunnen rekeningen worden afgesloten/stopgezet?
NEEN

. Kunnen gegevens van de klant worden aangepast?
NEEN

. Zijn er limieten bij storten/afhalen?
AFHALEN : SALDO EN KREDIETLIMIET, STORTEN : GEEN

. Welke locatie wordt bijgehouden/bepaald bij een verrichting (ip/plaatsnaam/...?
LOCATIE VAN HET KANTOOR

. Is het een keuze of je in het rood gaat / moet dit vooraf ingesteld worden?
DAS DE KREDIETLIMIET, IN TE STELLEN BIJ HET OPENEN VD REKENING

extra vraag


moet de leeftijdscontrole een extra stap zijn bij het basis pad? BuCRO stap 5




. Wie beslist over het kredietlimiet?
de klant bij het openen vd zictrekening

. Hoe wordt een rekeningnummer geformuleerd? Combinatie cijfers/letters bvb: BE123 123 123...
BExx 990y yyyy yyyy waarbij xx een controle nummer is en 990y yyyy yyyy een rekeningnummer is bestaande uit 12 cijfers. De 990 dient ter identificatie van de VSB. Voor het controlenummer kiezen we in deze opgave steeds 00 voor de eenvoud.

. Moet de klant een afschrift krijgen bij het afhalen of storten van geld?
ja

. Aan welke voorwaarden moet men voldoen bij het openen van een rekening? Ouder dan 12, belgische nationaliteit, geen openstaande schulden...
Je moet klant zijn (BElgisch rijksregisternr en 18jaar  of ouder

. Welke stappen moet een medewerker doorlopen om een zicht/spaarrekening aan te maken
de nodige informatie vragen aan de klant, cotitularissen checken en uniek rek nr aanmaken en mededelen

. Hoe verloopt het verificatieproces als een klant zijn bewijs van identiteit voorlegt.
* Antwoord:de klant controleert de identiteitskaart en checkt de foto

. Kan een klant voor iemand anders een rekening aanmaken? ( personen zijn niet gerelateerd)
neen, iedereen moet aanwezig zijn bij het openen

. Wordt de klant geinformeerd over de intrestvoet op spaarrekeningen / de de kredietvoet op zichtrekeningen?
ja, bij het openen

4:Waarom kan de kredietlimiet overschreden worden bij de aanrekening van kredietkosten?
ja, super goeie vraag!!!!

. Kan een klant een zichtrekening openen zonder krediet?
ja, dan is de kredietlimiet gewoon  0 Eur

. Moeten we rekening houden of de klant al dan niet eerder aangesloten was bij de bank?
als hij al eerder "aangesloten" was bij de bank, dan is het een klant vd bank en kan die klant alles doen wat andere klanten kunnen

. Heb ik een limiet op hoeveel ik per week kan uitgeven en kan ik deze verhogen    
geen limiet

. kan ik van mijn spaarrekening naar andere overschrijven 
ja, op voorwaarde dat de bestemming ook jouw rekening is bij de VSB (andere spaar of zicht rekening)

. Moeten co-titularissen ook aangesloten zijn als klant, zo nee welke gegevens moeten zij dan verplicht opgeven?
ja, ze moeten klant zijn


. Op welke manier kom ik te weten als er een cotitularies geld van mijn rekening heeft afgehaald?
in de uittreksels

. Zouden er extra kosten bijkomen als ik van bank beslis te veranderen?
Neen, maar je blijft klant voor het leven

. Wat gebeurd er als krediet niet kan terug betalen naar de bank in de periode dat afgesproken was? hoeveel extra kosten kan ik krijgen?
de bank maakt gewoon een overschrijving van je rekening voor de kosten, je kan daar zelf niks aan veranderen of tegenhouden. Je gaat dus gewoon NOG meer in het rood.
