== BUC_GA Geld Afhalen
De klant probeert geld af te halen. Er moet nagegaan worden hoeveel geld de klant op zijn rekening heeft staan, of dit genoeg is.

=== Actors
KLANT, MEDEWERKER

=== Preconditie 
Klant is geïdentificeerd

=== Basis pad 

    . De KLANT wil geld afhalen
    . De MEDEWERKER vraagt de klant voor zijn rekeningnummer
    . De KLANT geeft zijn rekeningnummer aan de medewerker
    . De MEDEWERKER gaat na of de klant wel een afhaling mag doen op die rekening volgens => link:domeinregels.adoc[DR_VGR,window=blank] en link:domeinregels.adoc[DR_AZR,window=blank]
    . De MEDEWERKER vraag aan de klant hoeveel geld hij wilt afhalen
    . De KLANT geeft aan hoeveel geld hij wilt afhalen
    . De MEDEWERKER gaat na of de klant het bedrag kan afhalen via => link:domeinregels.adoc[DR_VMB,window=blank]
    . De MEDEWERKER werkt het saldo van de rekening bij volgens => link:domeinregels.adoc[DR_VNS,window=blank] 
    . De MEDEWERKER noteert de transactie in de boekhouding => link:domeinregels.adoc[DR_VIB,window=blank]
    . De MEDEWERKER geeft het bedrag in cash aan de klant.
    . De use case eindigt

==== Postconditie
De klant heeft het bedrag cash gekregen, en is van zijn rekening afgehaald.

=== Alternatief A: Stoppen
    . De KLANT kan op elk moment beslissen om te stoppen.
    . De MEDEWERKER maakt eventuele wijzigingen ongedaan.
    . De use case eindigt.

==== Postconditie
Niets gewijzigd

=== Alternatief B: Klant mag geen geld van de opgegeven rekening halen.
[start = 4]
    . De MEDEWERKER stelt vast dat de klant geen geld mag afhalen van de opgegeven rekening.
    . De MEDEWERKER informeert de klant hierover.
    . De use case eindigt.

==== Postconditie
Niets gewijzigd

=== Alternatief C: Klant wil een te groot bedrag afhalen
[start = 7]
    . De MEDEWERKER merkt op dat de klant een te groot bedrag wilt afhalen.
    . De MEDEWERKER informeert de klant hierover.
    . De use case gaat verder met stap 5 van het basispad.

==== Postconditie
De klant is op de hoogte van zijn saldo, en kan dus alsnog beslissen om geld af te halen. Hij kan ook stoppen.

=== Representatieve Scenario’s

==== SC-GA-1 Basis Pad

Ashkan wil 200 euro afhalen van zijn zichtrekening met rekeningnummer BE00 0000 000 0000. 
Hij heeft nog 1000 euro op zijn zichtrekening staan en heeft een kredietlimiet van 500 euro. 
Hij is titularis van zijn rekeningen. 

Dit scenario volgt het basispad tot het einde.

==== SC-GA-2 Klant mag geen afhaling doen op de rekening

Ashkan wil 200 euro afhalen van zijn spaarrekening met rekeningnummer BE11 1111 111 1111. 
Hij heeft nog 1000 euro op zijn zichtrekening staan en heeft een kredietlimiet van 500 euro. 
Hij is titularis van zijn rekeningen. 

Dit scenario volgt het basispad tot in stap 4 en schakelt dan over naar alternatief B.

==== SC-GA-3 Klant wil een te groot bedrag afhalen

Ashkan wil 2000 euro afhalen van zijn zichtrekening met rekeningnummer BE00 0000 000 0000. 
Hij heeft nog 1000 euro op zijn zichtrekening staan en heeft een kredietlimiet van 500 euro. 
Hij is titularis van zijn rekeningen. 

Dit scenario volgt het basispad tot in stap 7 en schakelt dan over naar alternatief C.

==== SC-GA-4 Klant stopt

Ashkan wil 2000 euro afhalen van zijn zichtrekening met rekeningnummer BE00 0000 000 0000. 
Hij heeft nog 1000 euro op zijn zichtrekening staan en heeft een kredietlimiet van 500 euro. 
Hij is titularis van zijn rekeningen. 

Dit scenario volgt het basispad tot op het moment dat Askan beslist om te stoppen en schakelt dan over naar alternatief A.