[%autowidth]
|====
| link:..\verslag_groep_a01.adoc[Verslag]
|====

// titel '=' heeft speciale betekenis
//= Project "Vreemde Service Bank" Domeinregels

:toc:

== Domeinregels m.b.t. Rekeningen

=== Rekeningen Openen

==== *DR_GGC* : Gegevens Controle
De MEDEWERKER controleerd of de naam, voornaam, rijksregisternummer, straatnaam, huisnummer, postcode en gemeente correct zijn ingevult.

==== *DR_SKZ* Spaarrekening gekoppelt aan zichtrekening.
Elke spaarrekening moet gelinkt zijn aan een zichtrekening die toebehoort tot de titularis.

== Domeinregels m.b.t. Verrichtingen

=== Algemene verrichtingen

==== *DR_VMB* : Verrichting MaximumBedrag
Het maximumbedrag dat men kan verrichten vanuit een zichtrekening is de kredietlimiet van de zichtrekening + het resterend saldo van de zichtrekening.

==== *DR_VIB* : Verrichting In Boekhouding
Een financiele verrichting moet altijd bijgehouden worden in de boekhouding; deze transactie bevat de datum, de opdrachtgever, het bedrag, de betrokken rekening(en), de locatie en een optionele commentaar (max 20 karakters).

==== *DR_VGR* : Verrichting Geldige Rekening
Een verrichting kan gebeuren indien de uitgaande rekening in de VSB geregistreerd is.

==== *DR_VZR* : Verrichting ZichtRekening
Een verrichting kan enkel vanuit een zichtrekening gebeuren.

==== *DR_VTR* : Verrichting Toegang Rekening
Een verrichting kan gebeuren indien de opdrachtgever een (co-)titularis is.
