:toc:

== Afspraken vooraf

Om het ERM wat efficiënter te noteren, spreken het volgende af :

* elk attribuut is verplicht tenzij er expliciet "optioneel" bij staat
* elk attribuut laat dubbels toe, tenzij er expliciet "uniek" bij staat
* een rol wordt enkel getoond indien zij verschilt van de naam van de entiteitsklasse
    ** Bv. indien de rol van "Klant" in een relatie gewoon "klant" is dan vermelden we die rol niet
    ** Bv. indien de rol van "Klant" in een relatie "huurder" is, dan vermelden we die rol wel bij die relatie

== Entiteitsklassen

=== Klant

Alle personen waartoe we de klantgegevens geregistreerd hebben.

==== Attributen

* rijksregisternummer: Tekst, Uniek
    ** Het rijksregisternummer van deze klant.
* achternaam: Tekst
    ** De achternaam van deze klant.
* voornaam: Tekst
    ** De voornaam van deze klant.
* geboortedatum: Datum
    ** De geboortedatum van deze klant.

===== Constraints

=== Rekening

De rekening is een middel waarop de klant transacties kan verrichten.

==== Attributen

* rekeningnummer: Tekst, Uniek
    ** Dit is de unieke aangemaakte rekening die uit een landcode en 10 cijfers bestaat.
* kredietlimiet: Numeriek
    ** Is een maximum dat je mag opnemen van je rekening.

===== Constraints

=== Transactie

In het logboek worden alle gegevens over de verrichtingen bijgehouden.

==== Attributen

* tijdstip: Datum en Tijd
    ** Tijdstip van de transactie.
* rekening: Tekst
    ** Dit is de rekening van de klant. 
* bedrag: Numeriek
    ** Het bedrag waarmee je de transactie mee uitvoert.
* locatie: Tekst
    ** De locatie waar de transactie plaatsvindt. Bijvoorbeeld locatie thuis, geldautomaat, kantoor.

===== Constraints

== Relaties

=== Titularis-Rekening (1-N)

De klant is titularis van geen of meer rekeningen.

* Elke klant (rol: titularis) kan titularis zijn van één of meerdere rekeningen.
* Elke rekening moet één en enkel één titularis hebben.

=== Cotitularis-Rekening (N-M)

De klant is cotitularis van geen of meer rekeningen.

* Elke klant (rol: cotitularis) kan cotitularis zijn van één of meerdere rekeningen.
* Elke rekening kan één of meerdere cotitularissen hebben.

=== Transactie-Rekening (1-N)

Een transactie bevat gegevens van één rekening

* Elke transactie moet gegevens over één en enkel één rekening bevatten.
* Elke rekening kan één of meerdere transacties bevatten.

